#! /bin/sh

. /lib/partman/definitions.sh

[ -f /var/lib/partman/gptsync ] || exit 0

for dev in $(cat /var/lib/partman/gptsync); do
    [ -d "$dev" ] || continue
    device="$(cat "$dev/device")"
    log "gptsync $device"
    # TODO cjwatson 2007-01-13: e.g. gptsync --force would be a lot nicer
    if ! echo y | gptsync "$device"; then
	log "warning: gptsync $device failed"
    fi
done

exit 0
