#!/bin/sh

. /lib/partman/lib/base.sh

mypart=''
mysize=0

disks=
if db_get partman-auto/disk; then
	disks="$RET"
fi

for dev in $DEVICES/*; do
	[ -d $dev ] || continue
	if [ "$disks" ]; then
		disk="$(cat "$dev/device")"
		case " $disks " in
		    *" $disk "*)
			;;
		    *)
			continue
			;;
		esac
	fi
	cd $dev
	open_dialog PARTITIONS
	while { read_line num id size type fs path name; [ "$id" ]; }; do
		if [ "$fs" = free ] && [ "$type" != unusable ] && \
		   ! longint_le $size $mysize; then
			mysize=$size
			mypart=$dev//$id
		fi
	done
	close_dialog
done

if [ "$mypart" ]; then
	db_metaget partman-auto/text/use_biggest_free description
	printf "$mypart\t$RET"
fi
